"""refactor model Product

Revision ID: 1eed56acf976
Revises: 8dfe1c9b4332
Create Date: 2023-12-14 15:23:23.392696

"""
from typing import Sequence
from typing import Union

from alembic import op

# import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1eed56acf976"
down_revision: Union[str, None] = "8dfe1c9b4332"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "products", ["name"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "products", type_="unique")
    # ### end Alembic commands ###
