"""refactor models Order, Product, CartItem and create model Cart

Revision ID: 26f819d8083d
Revises: 9adca4ca3387
Create Date: 2023-12-16 12:45:37.519272

"""
from typing import Sequence
from typing import Union

import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "26f819d8083d"
down_revision: Union[str, None] = "9adca4ca3387"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "carts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column("cartitems", sa.Column("cart_id", sa.Integer(), nullable=False))
    op.create_foreign_key(None, "cartitems", "carts", ["cart_id"], ["id"])
    op.add_column("orders", sa.Column("cart_id", sa.Integer(), nullable=False))
    op.create_foreign_key(None, "orders", "carts", ["cart_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "orders", type_="foreignkey")
    op.drop_column("orders", "cart_id")
    op.drop_constraint(None, "cartitems", type_="foreignkey")
    op.drop_column("cartitems", "cart_id")
    op.drop_table("carts")
    # ### end Alembic commands ###
