"""add index to User.username

Revision ID: 525f16a0c97b
Revises: 48049658ced9
Create Date: 2023-12-12 15:51:17.975160

"""
from typing import Sequence
from typing import Union

from alembic import op

# import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "525f16a0c97b"
down_revision: Union[str, None] = "48049658ced9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("users_username_key", "users", type_="unique")
    op.create_index(op.f("ix_users_username"), "users", ["username"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_username"), table_name="users")
    op.create_unique_constraint("users_username_key", "users", ["username"])
    # ### end Alembic commands ###
