"""refactor models Order, Product, CartItem and create model Cart

Revision ID: 9adca4ca3387
Revises: de52fbb27f3f
Create Date: 2023-12-16 12:28:57.576577

"""
from typing import Sequence
from typing import Union

import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "9adca4ca3387"
down_revision: Union[str, None] = "de52fbb27f3f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cartitems",
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.Column("price", sa.Integer(), server_default="1", nullable=False),
        sa.Column("quantity", sa.Integer(), server_default="1", nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_table("orderitems")
    op.alter_column("orders", "coupon_id", existing_type=sa.INTEGER(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("orders", "coupon_id", existing_type=sa.INTEGER(), nullable=False)
    op.create_table(
        "orderitems",
        sa.Column("order_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("product_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "price",
            sa.INTEGER(),
            server_default=sa.text("1"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "quantity",
            sa.INTEGER(),
            server_default=sa.text("1"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(
            ["order_id"], ["orders.id"], name="orderitems_order_id_fkey"
        ),
        sa.ForeignKeyConstraint(
            ["product_id"], ["products.id"], name="orderitems_product_id_fkey"
        ),
        sa.PrimaryKeyConstraint("id", name="orderitems_pkey"),
    )
    op.drop_table("cartitems")
    # ### end Alembic commands ###
