"""refactor models Cart and User

Revision ID: c62dd51f516e
Revises: 26f819d8083d
Create Date: 2023-12-16 13:39:44.115803

"""
from typing import Sequence
from typing import Union

import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "c62dd51f516e"
down_revision: Union[str, None] = "26f819d8083d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("carts", sa.Column("user_id", sa.Integer(), nullable=False))
    op.create_foreign_key(None, "carts", "users", ["user_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "carts", type_="foreignkey")
    op.drop_column("carts", "user_id")
    # ### end Alembic commands ###
