"""refactor model Product

Revision ID: de52fbb27f3f
Revises: 1eed56acf976
Create Date: 2023-12-14 15:52:59.348992

"""
from typing import Sequence
from typing import Union

import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "de52fbb27f3f"
down_revision: Union[str, None] = "1eed56acf976"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("products", sa.Column("available", sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("products", "available")
    # ### end Alembic commands ###
