"""add orders to model User

Revision ID: f4b7e3ba9ef6
Revises: e382a38f99ff
Create Date: 2023-12-13 00:25:35.282660

"""
from typing import Sequence
from typing import Union

import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "f4b7e3ba9ef6"
down_revision: Union[str, None] = "e382a38f99ff"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("orders", sa.Column("user_id", sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("orders", "user_id")
    # ### end Alembic commands ###
